apiVersion: apps/v1
kind: Deployment
metadata:
  name: caculator-lab3
  namespace: uji-coba1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caculator-lab3
  template:
    metadata:
      labels:
        app: caculator-lab3
    spec:
      containers:
      - name: caculator-lab3
        image: registry-nexus.cloud/apps-lab3
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: admin-repo
---
apiVersion: v1
kind: Service
metadata:
  name: svc-caculator-lab3
  namespace: uji-coba1
spec:
  selector:
    app: caculator-lab3
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
